//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Response
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Không được để trông tên phản hồi")]
        [MaxLength(50,ErrorMessage ="Tên không được quá 50 kí tự")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập email của bạn")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên công ty")]
        public string CompanyName { get; set; }
        [Required(ErrorMessage = "Nội dung phản hồi không được để trống")]
        public string Subject { get; set; }
    }
}
